// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *continent → cities*
 */
export interface ContinentDocumentDataCitiesItem {
  /**
   * image field in *continent → cities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.cities[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *continent → cities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.cities[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * country field in *continent → cities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.cities[].country
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  country: prismic.RichTextField;

  /**
   * flag country field in *continent → cities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.cities[].flag_country
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  flag_country: prismic.ImageField<never>;
}

/**
 * Content for continent documents
 */
interface ContinentDocumentData {
  /**
   * Banner field in *continent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * title field in *continent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *continent*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField;

  /**
   * content field in *continent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * quantity countries field in *continent*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.quantity_countries
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  quantity_countries: prismic.NumberField;

  /**
   * quantity cities field in *continent*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.quantity_cities
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  quantity_cities: prismic.NumberField;

  /**
   * quantity languages field in *continent*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.quantity_languages
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  quantity_languages: prismic.NumberField;

  /**
   * cities field in *continent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: continent.cities[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cities: prismic.GroupField<Simplify<ContinentDocumentDataCitiesItem>>;
}

/**
 * continent document from Prismic
 *
 * - **API ID**: `continent`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContinentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContinentDocumentData>,
    "continent",
    Lang
  >;

export type AllDocumentTypes = ContinentDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContinentDocument,
      ContinentDocumentData,
      ContinentDocumentDataCitiesItem,
      AllDocumentTypes,
    };
  }
}
